
version: '3'

services:

  api:
    build: .
    command: >
      sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:9000"
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - postgres
      - migration
    volumes:
      - .:/app
      - static_volume:/usr/src/app/back_static
      - media_volume:/usr/src/app/back_media

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  migration:
    build: .
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx_eco
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/back_static
      - media_volume:/usr/src/app/back_media
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume:
